name: Sheep
main: Sheep\SheepPlugin
version: 5.2.3
api: [3.0.0]

author: KnownUnown
description: A plugin for [installing, uninstalling, viewing] other plugins.
website: https://www.github.com/KnownUnown/Sheep
